# Site settings
baseurl = "https://arcfu.com/"
languageCode = "en-us"
title = "Aman Rusia"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = ""

[params]
	name = "Aman Rusia"
	description = "Personal blog and portfolio"
	bio = "I work in the Artificial Intelligence field and I write about interesting things I encounter in professional life and otherwise. I am also interested in scientific methods and rationalism."
	# Enter optionally your twitter account
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = ["css/dark-theme.css", "css/sea-background.css", "css/button-override.css"]
	customJS  = ["js/bioluminescent-sea.js", "js/animation-controls.js", "js/page-transition.js"]

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "I'm a human, an engineer, and aspiring new age rationalist."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"
    
    # Social links (moved from [social] to [params] for newer Hugo versions)
    [params.social]
        github   = "https://www.github.com/rusiaaman"
        linkedin = "https://linkedin.com/in/rusiaaman"
